### ISSUE TITLE
Error (Warn) in my console ! :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Matsv/ViaBackwards#52]
Hey ! :D

I have an error (a warn): https://hastebin.com/besugusigo.scala ! :D 

Could you fix it ? :D 
Thanks ! :D

**Comment by Matsv** [comment]
One of your plugins is sending wrong metadata. This could be because a plugin is outdated, or just sends wrong data without reason.
I’d recommend debugging your plugins by removing them one by one until it no longer happens to find out which one is causing this. You can also ignore this warning by changing ‘suppress-metadata-errors’ to ‘true’ in the ViaVersion config.
