### ISSUE TITLE
Getting with spam on bungee console warnings

### ISSUE THREAD

**Issue by NeximaOzi** [Matsv/ViaBackwards#85]
### What is the output url of /viaversion dump?
> ViaBackWards: Latest (2.3.1)
> ViaVersion: Latest (1.6.0)

### How/when does this error happen? login?:
> I don't know

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/YFsWz27q

**Comment by Matsv** [comment]
One of your plugins is sending wrong metadata. This could be because a plugin is outdated, or just sends wrong data without reason.
I’d recommend debugging your plugins by removing them one by one until it no longer happens to find out which one is causing this. You can also ignore this warning by changing ‘suppress-metadata-errors’ to ‘true’ in the ViaVersion config.
